Repository kubevirt/kubevirt-template-validator, pull requests merged in 2020-12, with the labels that each got.

#58 update error message for integer rule
  pkg/validation/specialized.go
  pkg/validation/specialized_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#56 Allow usage of hack/build/build.sh when not in a git repo
  hack/build/build.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#53 Add support for vm validation annotation
  functests/03-test-with-template-with-rules-satisfied.sh
  functests/15-test-vm-with-validations-template-without-validations.sh
  functests/16-test-vm-with-validations-template-with-validations.sh
  functests/17-test-vm-with-validations-no-template.sh
  functests/manifests/15-template-without-validations-vm-with-validations/template-without-rules.yaml
  functests/manifests/15-template-without-validations-vm-with-validations/vm-with-validation-rules-failing.yaml
  functests/manifests/15-template-without-validations-vm-with-validations/vm-with-validation-rules-passing.yaml
  functests/manifests/16-template-with-validations-vm-with-validations/template-with-rules.yaml
  functests/manifests/16-template-with-validations-vm-with-validations/vm-with-validation-rules-failing.yaml
  functests/manifests/16-template-with-validations-vm-with-validations/vm-with-validation-rules-passing.yaml
  functests/manifests/17-vm-with-validations-no-template/vm-with-validation-rules-deleted-template-failing.yaml
  functests/manifests/17-vm-with-validations-no-template/vm-with-validation-rules-deleted-template-passing.yaml
  functests/manifests/17-vm-with-validations-no-template/vm-with-validation-rules-without-template-failing.yaml
  functests/manifests/17-vm-with-validations-no-template/vm-with-validation-rules-without-template-passing.yaml
  go.sum
  pkg/webhooks/validating/admission_test.go
  pkg/webhooks/validating/uplink.go
  pkg/webhooks/validating/validating_suite_test.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL
